[package]
name = "fxc-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
eframe = "0.28.1"
tokio = { version = "1.39.2", features = ["full"] }
rfd = "0.14.1"


[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
winres = "0.1"